server:
  port: 7070
spring:
  application:
    name: app-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      routes:
        - id: app-user-8000 #自定义路由名称
          uri: http://www.ityouknow.com
#          uri: lb://app-user   # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
          predicates: #转发路径规则
            - Path=/GUSER/**
        - id: app-order-9000
          uri: lb://app-order
          predicates:
            - Path=/GORDER/**
    nacos:
      server-addr: localhost:8848

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka/
#logging:
#  level:
#    root: debug
